-- 1. Create Schema
CREATE SCHEMA api;

-- 2. Create Tables
create table api.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

insert into api.todos (task) values
  ('finish tutorial 0'), ('pat self on back');

-- 3. Create Roles
create role web_anon nologin;

grant usage on schema api to web_anon;
grant all on api.todos to web_anon;
