-- Create the 'todos' table within the 'api' schema
CREATE TABLE api.todos (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    done boolean NOT NULL DEFAULT false,
    task text NOT NULL,
    due timestamptz
);

-- Insert sample tasks into the 'todos' table
INSERT INTO api.todos (task) VALUES
    ('finish tutorial 0'),
    ('pat self on back');